import Head from 'next/head';
import { HeroItem, Navbar } from '@/components';

import { useSession } from 'next-auth/react';

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#FCFCFC]">
        <Navbar />
        <HeroItem />
        {session ? <>Signin as {session.user.name}</> : <>Login</>}
        <h1>Halamana Utama </h1>
      </main>
    </>
  );
}
